# Generated by Django 5.0.6 on 2024-06-19 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное имя пользователя. Это значение может содержать только буквы, цифры, пробелы и символы @/./+/-/_.', regex='^[\\w.@+-\\u0400-\\u04FF\\s]+$')]),
        ),
    ]
