# Generated by Django 5.0.6 on 2024-06-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Parent'), (2, 'Student'), (3, 'Teacher')], default=1),
        ),
    ]
