# Generated by Django 5.0.6 on 2024-06-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parent'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseapplication'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topic'),
        ),
    ]
