# Generated by Django 5.0.6 on 2024-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
